/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileViewerRouteImport } from './routes/mobile-viewer'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UiConceptsRouteImport } from './routes/ui-concepts'
import { Route as UiPreviewRouteImport } from './routes/ui-preview'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as GridLessonLessonIdRouteImport } from './routes/grid-lesson.$lessonId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as ReadSpellTopicIdRouteImport } from './routes/read-spell.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewerRoute = MobileViewerRouteImport.update({
  id: '/mobile-viewer',
  path: '/mobile-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UiConceptsRoute = UiConceptsRouteImport.update({
  id: '/ui-concepts',
  path: '/ui-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPreviewRoute = UiPreviewRouteImport.update({
  id: '/ui-preview',
  path: '/ui-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const GridLessonLessonIdRoute = GridLessonLessonIdRouteImport.update({
  id: '/grid-lesson/$lessonId',
  path: '/grid-lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSpellTopicIdRoute = ReadSpellTopicIdRouteImport.update({
  id: '/read-spell/$topicId',
  path: '/read-spell/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mobile-viewer': typeof MobileViewerRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ui-concepts': typeof UiConceptsRoute
  '/ui-preview': typeof UiPreviewRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/grid-lesson/$lessonId': typeof GridLessonLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/read-spell/$topicId': typeof ReadSpellTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mobile-viewer': typeof MobileViewerRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ui-concepts': typeof UiConceptsRoute
  '/ui-preview': typeof UiPreviewRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/grid-lesson/$lessonId': typeof GridLessonLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/read-spell/$topicId': typeof ReadSpellTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mobile-viewer': typeof MobileViewerRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ui-concepts': typeof UiConceptsRoute
  '/ui-preview': typeof UiPreviewRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/grid-lesson/$lessonId': typeof GridLessonLessonIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/read-spell/$topicId': typeof ReadSpellTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/dictionary'
    | '/home'
    | '/learn'
    | '/login'
    | '/mobile-viewer'
    | '/practice'
    | '/profile'
    | '/ui-concepts'
    | '/ui-preview'
    | '/api/chat'
    | '/category/$categoryId'
    | '/grid-lesson/$lessonId'
    | '/lesson/$lessonId'
    | '/read-spell/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/dictionary'
    | '/home'
    | '/learn'
    | '/login'
    | '/mobile-viewer'
    | '/practice'
    | '/profile'
    | '/ui-concepts'
    | '/ui-preview'
    | '/api/chat'
    | '/category/$categoryId'
    | '/grid-lesson/$lessonId'
    | '/lesson/$lessonId'
    | '/read-spell/$topicId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/dictionary'
    | '/home'
    | '/learn'
    | '/login'
    | '/mobile-viewer'
    | '/practice'
    | '/profile'
    | '/ui-concepts'
    | '/ui-preview'
    | '/api/chat'
    | '/category/$categoryId'
    | '/grid-lesson/$lessonId'
    | '/lesson/$lessonId'
    | '/read-spell/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  DictionaryRoute: typeof DictionaryRoute
  HomeRoute: typeof HomeRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MobileViewerRoute: typeof MobileViewerRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  UiConceptsRoute: typeof UiConceptsRoute
  UiPreviewRoute: typeof UiPreviewRoute
  ApiChatRoute: typeof ApiChatRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  GridLessonLessonIdRoute: typeof GridLessonLessonIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  ReadSpellTopicIdRoute: typeof ReadSpellTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-viewer': {
      id: '/mobile-viewer'
      path: '/mobile-viewer'
      fullPath: '/mobile-viewer'
      preLoaderRoute: typeof MobileViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-concepts': {
      id: '/ui-concepts'
      path: '/ui-concepts'
      fullPath: '/ui-concepts'
      preLoaderRoute: typeof UiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-preview': {
      id: '/ui-preview'
      path: '/ui-preview'
      fullPath: '/ui-preview'
      preLoaderRoute: typeof UiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-lesson/$lessonId': {
      id: '/grid-lesson/$lessonId'
      path: '/grid-lesson/$lessonId'
      fullPath: '/grid-lesson/$lessonId'
      preLoaderRoute: typeof GridLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read-spell/$topicId': {
      id: '/read-spell/$topicId'
      path: '/read-spell/$topicId'
      fullPath: '/read-spell/$topicId'
      preLoaderRoute: typeof ReadSpellTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  DictionaryRoute: DictionaryRoute,
  HomeRoute: HomeRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MobileViewerRoute: MobileViewerRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  UiConceptsRoute: UiConceptsRoute,
  UiPreviewRoute: UiPreviewRoute,
  ApiChatRoute: ApiChatRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  GridLessonLessonIdRoute: GridLessonLessonIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  ReadSpellTopicIdRoute: ReadSpellTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
