const fs = require("fs");
const path = require("path");
const https = require("https");

// Node 20.6+ can load .env without adding a runtime dependency.
const ENV_PATH = path.join(__dirname, "../.env");
if (typeof process.loadEnvFile === "function" && fs.existsSync(ENV_PATH)) {
  process.loadEnvFile(ENV_PATH);
}

// Config
const API_KEY = process.env.AZURE_TTS_API_KEY;
const REGION = process.env.AZURE_TTS_REGION || "southeastasia";
const OUTPUT_FORMAT = process.env.AZURE_TTS_FORMAT || "audio-16khz-64kbitrate-mono-mp3";
const OUTPUT_DIR = path.join(__dirname, "../public/audio/anki"); // or just public/audio
const SYLLABUS_PATH = path.join(__dirname, "../src/lib/contentSyllabus.json");
const DRY_RUN = process.argv.includes("--dry-run");
const SAFE_CHARACTER_LIMIT = 450000;

if (!DRY_RUN && !API_KEY) {
  console.error("❌ ERROR: AZURE_TTS_API_KEY is missing in .env file.");
  console.error("Please add it: AZURE_TTS_API_KEY=your_key_here");
  process.exit(1);
}

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Read syllabus
let syllabus;
try {
  const data = fs.readFileSync(SYLLABUS_PATH, "utf8");
  syllabus = JSON.parse(data);
} catch (error) {
  console.error("❌ ERROR: Could not read or parse src/lib/contentSyllabus.json", error);
  process.exit(1);
}

// Extract tasks
const tasks = [];
syllabus.modules.forEach((module, index) => {
  module.data.forEach((item) => {
    if (item.audio) {
      let textToSpeak = "";
      if (item.text) textToSpeak = item.text;
      else if (item.word) textToSpeak = item.word;
      else if (item.khmer) textToSpeak = item.khmer;
      else if (item.content_km) textToSpeak = item.content_km;
      else if (item.q_text) textToSpeak = item.q_text;

      // Handle listening/reading test audio that might point to existing audio
      // In module 5, we have q_audio, which points to m3_X or m1_X. We don't need to re-download those,
      // they are already generated by module 1 or 3. So only download if we actually have text in this item.

      if (textToSpeak && textToSpeak.trim().length > 0) {
        // Default to Piseth if voice is not specified
        const voice = item.voice || "km-KH-PisethNeural";
        tasks.push({
          filename: item.audio,
          text: textToSpeak,
          voice: voice,
          id: item.id,
        });
      }
    }
  });
});

console.log(`✅ Found ${tasks.length} audio files to generate.`);

function generateAudio(task) {
  return new Promise((resolve, reject) => {
    const destPath = path.join(OUTPUT_DIR, task.filename);

    // Skip if already exists
    if (fs.existsSync(destPath)) {
      console.log(`⏭️  Skipping ${task.filename} (already exists)`);
      return resolve();
    }

    const ssml = `<speak version='1.0' xml:lang='km-KH'><voice xml:lang='km-KH' name='${task.voice}'>${task.text}</voice></speak>`;

    const options = {
      hostname: `${REGION}.tts.speech.microsoft.com`,
      path: "/cognitiveservices/v1",
      method: "POST",
      headers: {
        "Ocp-Apim-Subscription-Key": API_KEY,
        "Content-Type": "application/ssml+xml",
        "X-Microsoft-OutputFormat": OUTPUT_FORMAT,
        "User-Agent": "SalaKhmer",
      },
    };

    const req = https.request(options, (res) => {
      if (res.statusCode !== 200) {
        let errorData = "";
        res.on("data", (chunk) => {
          errorData += chunk;
        });
        res.on("end", () => {
          console.error(
            `❌ ERROR fetching ${task.filename}: HTTP ${res.statusCode} - ${errorData}`,
          );
          reject(new Error(`HTTP ${res.statusCode}`));
        });
        return;
      }

      const fileStream = fs.createWriteStream(destPath);
      res.pipe(fileStream);

      fileStream.on("finish", () => {
        fileStream.close();
        console.log(`⬇️  Downloaded ${task.filename} (${task.text})`);
        resolve();
      });

      fileStream.on("error", (err) => {
        console.error(`❌ ERROR writing ${task.filename}:`, err);
        fs.unlink(destPath, () => {});
        reject(err);
      });
    });

    req.on("error", (err) => {
      console.error(`❌ Network ERROR for ${task.filename}:`, err);
      reject(err);
    });

    req.write(ssml);
    req.end();
  });
}

// Process sequentially to avoid rate limits
async function processTasks() {
  for (let i = 0; i < tasks.length; i++) {
    try {
      await generateAudio(tasks[i]);
      // Small delay between requests
      await new Promise((r) => setTimeout(r, 200));
    } catch (err) {
      console.error(`Stopping due to error on task ${i + 1}/${tasks.length}`);
      break;
    }
  }
  console.log("🎉 Finished processing all audio tasks.");
}

function printDryRunReport() {
  const synthesisKeys = new Map();
  const duplicates = [];

  for (const task of tasks) {
    const key = `${task.voice}::${task.text.trim()}`;
    if (synthesisKeys.has(key)) duplicates.push(task);
    else synthesisKeys.set(key, task);
  }

  const uniqueTasks = [...synthesisKeys.values()];
  const existingFiles = uniqueTasks.filter((task) =>
    fs.existsSync(path.join(OUTPUT_DIR, task.filename)),
  );
  const plannedFiles = uniqueTasks.filter(
    (task) => !fs.existsSync(path.join(OUTPUT_DIR, task.filename)),
  );
  // The request only wraps text in <speak> and <voice>, which Azure excludes from billing.
  const characters = plannedFiles.reduce((total, task) => total + Array.from(task.text).length, 0);

  console.log("\nSalaKhmer Azure audio dry-run");
  console.log("===============================");
  console.log(`Output format: ${OUTPUT_FORMAT}`);
  console.log(`Source entries with audio: ${tasks.length}`);
  console.log(`Unique synthesis requests: ${uniqueTasks.length}`);
  console.log(`Duplicate text/voice requests: ${duplicates.length}`);
  console.log(`Already generated files: ${existingFiles.length}`);
  console.log(`Files to generate: ${plannedFiles.length}`);
  console.log(`Estimated Azure billable characters: ${characters}`);
  console.log(`Safety limit: ${SAFE_CHARACTER_LIMIT}`);
  console.log(`Within safety limit: ${characters <= SAFE_CHARACTER_LIMIT ? "YES" : "NO"}`);

  if (characters > SAFE_CHARACTER_LIMIT) {
    console.error("ABORT: planned synthesis exceeds the safety limit. Split the batch first.");
    process.exitCode = 2;
  }
}

if (DRY_RUN) {
  printDryRunReport();
} else {
  processTasks();
}
